In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
# How many negtive numbers are there?

a[a < 0]

array([-2, -1, -6, -7])

In [18]:
# How many positive numbers are there?

only_pos = a[a > 0]
only_pos

array([ 4, 10, 12, 23,  3])

In [200]:
# How many even positive numbers are there?

# only_pos[only_pos % 2 ==0]

len(a[(a > 0) & (a % 2 == 0)])

5

In [199]:
# If you were to add 3 to each data point, how many positive numbers would there be?

new_a = a + 3
len(new_a[new_a > 0])

10

In [26]:
# If you squared each number, what would the new mean and standard deviation be?

new_a = a**2
new_a.mean(), new_a.std()

(74.0, 144.0243035046516)

In [28]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.

x = a.mean()
new_a = a - x
new_a.mean()

0.0

In [30]:
# Calculate the z-score for each data point.

x = a.mean()
y = a.std()
new_a = (a - x)/y
new_a

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [201]:
import numpy as np

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = np.array(a)

In [202]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all 
# the numbers in above list

sum(a)

55

In [203]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all 
# the numbers in the above list

min(a)

1

In [204]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all 
# the numbers in the above list

max(a)

10

In [205]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all 
# the numbers in the above list

mean_of_a = a.mean()
mean_of_a

5.5

In [55]:
# Exercise 5 - Make a variable named product_of_a to hold the product of 
# multiplying all the numbers in the above list together

product_of_a = np.prod(a)
product_of_a

3628800

In [58]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each 
# number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [59]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [60]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [103]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [107]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [207]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

b.sum()

33

In [85]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

np.min(b)

3

In [84]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

np.max(b)

8

In [82]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

np.mean(b)

5.5

In [86]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

np.prod(b)

20160

In [89]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [208]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

b[b % 2 != 0]

array([3, 5, 7])

In [209]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

b[b % 2 == 0]

array([4, 6, 8])

In [108]:
# Exercise 9 - print out the shape of the array b.

print(b.shape)

(2, 3)


In [109]:
# Exercise 10 - transpose the array b.

print(b.transpose())

[[3 6]
 [4 7]
 [5 8]]


In [210]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [211]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [212]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [213]:
c = np.array(c)

In [214]:
# Exercise 1 - Find the min, max, sum, and product of c.

np.min(c), np.max(c), np.sum(c), np.product(c)

(1, 9, 45, 362880)

In [215]:
# Exercise 2 - Determine the standard deviation of c.

np.std(c)

2.581988897471611

In [216]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [123]:
# Exercise 4 - Print out the shape of the array c

print(np.shape(c))

(3, 3)


In [127]:
# Exercise 5 - Transpose c and print out transposed result.

print(np.transpose(c))


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [128]:
# Exercise 6 - Get the dot product of the array c with c.

np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [139]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. 
# Answer should be 261

np.sum(c * np.transpose(c))

261

In [141]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed.
# Answer should be 131681894400.

np.product(c * np.transpose(c))

131681894400

In [173]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [177]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [146]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [147]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [148]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [182]:
# Exercise 4 - Find all the negative numbers in d

new_d = d.reshape(1,18)
new_d
new_d[new_d < 0]

array([-90, -30, -45, -45])

In [183]:
# Exercise 5 - Find all the positive numbers in d

new_d = d.reshape(1,18)
new_d
new_d[new_d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [187]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [197]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))


11

In [194]:
# Exercise 8 - Print out the shape of d.

np.shape(d)

(3, 6)

In [195]:
# Exercise 9 - Transpose and then print out the shape of d.

np.transpose(d)

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [196]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])